package domain.entity

import kotlinx.datetime.LocalDateTime

data class FireItems(
    val id: Int,
    val name: String? = null,
    val price: Float,
    val totalPrice: Float,
    val qty: Float,
    val noServiceCharge: Boolean,
    val isModifier: Boolean,
    val taxable: Boolean,
    val pickFollowItemQty: Boolean,
    val modifierGroupID: Int,
    val prePaidCard: Boolean,
    val ws: Int,
    val pOnReport: Boolean? = null,
    val checkId: Long? = null,
    val itemId: Int? = null,
    val unitPrice: Float? = null,
    val discountValue: Float? = null,
    val taxValue: Float? = null,
    val adjValue: Float? = null,
    val netPrice: Float? = null,
    val serial: Int? = null,
    val fired: Boolean? = null,
    val firedTime: LocalDateTime? = null,
    val voided: Boolean? = null,
    val voidedTime: LocalDateTime? = null,
    val voidedReason: Int? = null,
    val pOnCheck: Boolean? = null,
    val complement: Float? = null,
    val status: String? = null,
    val refModItem: Int? = null,
    val isAssembly: Boolean? = null,
    val refAssItem: Int? = null,
    val numFired: Int? = null,
    val numPrint: Int? = null,
    val serverId: Int? = null,
    val checkIdCombine: Long? = null,
    val roundCheckFired: Int? = null,
    val voidEffectInvn: Boolean? = null,
    val promoId: Int? = null,
    val origPrice: Float? = null,
    val officer: Float? = null,
    val compReasonId: Int? = null,
    val endSerialCount: Long? = null,
    val discountId: Int? = null,
    val discReasonId: Int? = null,
    val hold: Boolean? = null,
    val holdTime: LocalDateTime? = null,
    val voidedBy: Int? = null,
    val compBy: Int? = null,
    val discBy: Int? = null,
    val preparationTime: Int? = null,
    val discReasonComment: String? = null,
    val compReasonComment: String? = null,
    val voidReasonComment: String? = null,
    val modifierGroupId: Int? = null,
    val modifierPick: Int? = null,
    val userId: Int? = null
)