package domain.entity

import kotlinx.datetime.LocalDateTime

data class Item(
    val id: Int,
    val code: String,
    val name: String,
    val name2: String,
    val barCode: String,
    val crossCode: Int,
    val taxable: Boolean,
    val assembly: Boolean,
    val subCategoryId: Int,
    val isModifier: Boolean,
    val standAlone: Boolean,
    val printOnChick: Boolean,
    val printOnReport: Boolean,
    val followItem: Boolean,
    val imageItem: ByteArray?,
    val cost: Float,
    val openPrice: Boolean,
    val staticPrice: Float,
    val description1: String,
    val description2: String,
    val description3: String,
    val description4: String,
    val modPrice0: Boolean,
    val useItemTimer: Boolean,
    val itemTimerValue: Int,
    val active: Boolean,
    val createDate: LocalDateTime,
    val modifiedDate: LocalDateTime,
    val userId: Int,
    val noServiceCharge: Boolean,
    val marketPrice: Boolean,
    val itemTrack: Boolean,
    val printItemOnCheck: Boolean,
    val isParent: Boolean,
    val restIdActive: Int,
    val openFood: Boolean,
    val modPrice: Float,
    val prePaidCard: Boolean,
    val modifierCount: Int
)