package domain.entity

data class ModifierItem(
    val code: String,
    val name: String,
    val name2: String,
    val modCount: Int,
    val taxable: Boolean,
    val assimbly: Boolean,
    val noServiceCharge: Boolean,
    val isModifier: Boolean,
    val standAlone: Boolean,
    val printOnChick: Boolean,
    val printOnReport: Boolean,
    val printItemOnCheck: Boolean,
    val followItem: Boolean,
    val openPrice: Boolean,
    val staticPrice: Float,
    val openFood: Boolean,
    val modPrice: Float,
    val modPrice0: Boolean,
    val useItemTimer: Boolean,
    val itemTimerValue: Int,
    val itemID: Int,
    val modifierGroupName: String,
    val modifierGroupName2: String,
    val multiPick: Boolean,
    val maxPick: Int,
    val allowNoPick: Boolean,
    val modifierGroupID: Int,
    val prePaidCard: Boolean,
    val pickFollowItemQty: Boolean,
    val multiChooseForSameMod: Boolean,
)