package resource.strings

interface IStringResources {
    val click: String
    val logo: String
    val login: String
    val logout: String
    val admin: String
    val exit: String
    val dinningIn: String
    val outlet: String
    val settings: String
    val userName: String
    val password: String
    val ok: String
    val cancel: String
    val tryAgain: String
    val somethingWrongHappened: String
    val noInternetMessage: String
    val noInternetDescription: String
    val nullDataMessage: String
    val nullDataDescription: String
    val enterYourInfo: String
    val warning: String
    val error: String
    val userNotFound: String
    val enterYourPasscode: String
    val retry: String
    val passcode: String
    val userNameEmptyException: String
    val passwordEmptyException: String
    val passcodeEmptyException: String
    val authEmptyException: String
    val doYouWantToCloseApp: String
    val covers: String
    val welcome: String
    val bye: String
    val itemAddedSuccess: String
    val alreadyOpenChecks: String
}